%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters.
# Config file made based on the euroc_mono.yml from the orb_slam3_ros package
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Get from /realsense/color/camera_info topic and the Gazebo plugin parameters in
# github.com/husky/husky/blob/noetic-devel/husky_description/urdf/accessories/intel_realsense.urdf.xacro
Camera1.fx: 337.2084410968044
Camera1.fy: 337.2084410968044
Camera1.cx: 320.5
Camera1.cy: 240.5

Camera1.k1: 0.00000001
Camera1.k2: 0.00000001
Camera1.p1: 0.00000001
Camera1.p2: 0.00000001
Camera1.k3: 0.00000001

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 50.0
Stereo.b: 0.07732

# Depth map values factor
RGBD.DepthMapFactor: 1.0 # 1.0 for ROS_bag

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
